#!/usr/bin/env node
/**
 * gen-samples — generate docs/guide/samples.md from the shipped sample gallery.
 *
 * WHY THIS EXISTS
 * ---------------
 * cap2UI5 ships over a hundred sample apps, and until this page existed the
 * only way into them was to already know a class name and hand-type it into
 * `?app_start=`. A hand-written index would have been a second copy of a list
 * that changes on every sync — stale within a week, and invisible to
 * verify-refs until a class actually disappeared.
 *
 * So the page is generated from the gallery itself. `z2ui5_cl_smp_app_000` is
 * the sample browser that ships with the framework; its `get_catalog()` holds
 * one `{ group, header, sub, keywords, path, app }` entry per sample. That
 * table is the same source the in-app gallery renders from, which makes it the
 * only list that cannot disagree with what the playground actually offers.
 *
 * Usage:
 *   CAP2UI5_DIR=/path/to/cap2UI5 node scripts/gen-samples.mjs
 *   node scripts/gen-samples.mjs           # defaults to ../cap2UI5
 *   node scripts/gen-samples.mjs --check   # fail if the page is out of date
 *
 * The result is committed like any other page: the docs must build without a
 * cap2UI5 checkout, and a reviewer should see the diff a sync causes.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const APP = path.resolve(process.env.CAP2UI5_DIR || path.join(ROOT, "..", "cap2UI5"));
const SAMPLES = path.join(APP, "core", "srv", "app", "samples");
const GALLERY = "z2ui5_cl_smp_app_000";
const OUT = path.join(ROOT, "docs", "guide", "samples.md");
const CHECK = process.argv.includes("--check");

const PLAYGROUND = "https://cap2ui5.github.io/web-cap2UI5-build/";
const SOURCE = "https://github.com/cap2UI5/cap2UI5/blob/main/core/srv/app/samples";

if (!fs.existsSync(path.join(SAMPLES, `${GALLERY}.js`))) {
  console.error(`gen-samples: no sample gallery at ${SAMPLES}/${GALLERY}.js`);
  console.error(`             set CAP2UI5_DIR or clone cap2UI5/cap2UI5 next to this repo.`);
  process.exit(1);
}

// The catalogue is one long array literal of object literals, all fields in a
// fixed order because the file is machine-generated by the transpiler. Parsing
// it with a regex is fine for exactly that reason — and if the shape ever
// changes, the count check below turns the surprise into a failure.
const ENTRY_RE =
  /\{ group: `([^`]*)`, header: `([^`]*)`, sub: `([^`]*)`, keywords: `([^`]*)`, path: `([^`]*)`, app: `([^`]*)` \}/g;

const src = fs.readFileSync(path.join(SAMPLES, `${GALLERY}.js`), "utf8");
const entries = [...src.matchAll(ENTRY_RE)].map((m) => ({
  group: m[1],
  header: m[2],
  sub: m[3],
  keywords: m[4],
  app: m[6],
}));

if (entries.length < 50) {
  console.error(`gen-samples: only ${entries.length} catalogue entries parsed from ${GALLERY}.js`);
  console.error(`             the gallery table's shape probably changed — fix ENTRY_RE.`);
  process.exit(1);
}

const files = new Set(
  fs
    .readdirSync(SAMPLES)
    .filter((f) => f.endsWith(".js"))
    .map((f) => f.slice(0, -3)),
);

const missing = entries.filter((e) => !files.has(e.app));
if (missing.length) {
  console.error(`gen-samples: the gallery lists ${missing.length} class(es) with no file:`);
  for (const e of missing) console.error(`  ${e.app}`);
  process.exit(1);
}

// The `group` field separates the upstream sample repositories (samples,
// controls, stack). Only one of them is carried into the port today, so
// grouping by it yields a single bucket — the useful axis is `header`, the
// category the in-app gallery prints above each block. Both are honoured:
// groups first (in catalogue order), categories inside them.
//
// One presentation liberty: the gallery numbers its introductory tiles
// `Basics I` … `Basics V`, one sample each. Five one-row tables is noise on a
// page you scroll rather than search, so they collapse into one `Basics`
// section — in catalogue order, which is the order they are meant to be read.
const categoryOf = (header) => (/^Basics\b/.test(header) ? `Basics` : header);

const groups = [];
for (const e of entries) {
  let g = groups.find((x) => x.name === e.group);
  if (!g) groups.push((g = { name: e.group, categories: [] }));
  const name = categoryOf(e.header);
  let c = g.categories.find((x) => x.name === name);
  if (!c) g.categories.push((c = { name, rows: [] }));
  c.rows.push(e);
}

const md = (s) => s.replace(/\|/g, "\\|");
const anchor = (s) =>
  s
    .toLowerCase()
    .replace(/[^\w\- ]+/g, "")
    .replace(/ /g, "-");

const categories = groups.flatMap((g) => g.categories);
const uncatalogued = [...files].filter((f) => f !== GALLERY && !entries.some((e) => e.app === f)).sort();

const out = [];
out.push(`<!-- GENERATED by scripts/gen-samples.mjs — do not edit by hand. -->`);
out.push(`<!-- Regenerate with: CAP2UI5_DIR=/path/to/cap2UI5 npm run gen:samples -->`);
out.push(``);
out.push(`# Sample Catalogue`);
out.push(``);
out.push(
  `The framework ships ${files.size} sample apps in \`core/srv/app/samples/\` — the ` +
    `abap2UI5 demo collection, transpiled to JavaScript. ${entries.length} of them are ` +
    `listed in the built-in gallery, and this page is that gallery's own table: it is ` +
    `generated from \`${GALLERY}\`, the sample browser the framework itself renders, so it ` +
    `cannot drift from what the playground offers.`,
);
out.push(``);
out.push(
  `Every title links into the [browser playground](./playground) — no install, no server. ` +
    `The same apps run on your own CAP server under the same names: ` +
    `\`?app_start=<class>\`, or \`client.nav_app_call()\` from an app of your own.`,
);
out.push(``);
out.push(
  `→ Prefer to browse in the app itself? Open ` +
    `[\`${GALLERY}\`](${PLAYGROUND}?app_start=${GALLERY}) — the same catalogue with a search field.`,
);
out.push(``);
out.push(
  `Two markers are carried over from the upstream gallery: **(A)** marks a sample that ` +
    `drives the frontend through a client action, **(C)** one that uses a custom control ` +
    `from the \`z2ui5.cc\` namespace.`,
);
out.push(``);
out.push(`## Categories`);
out.push(``);
out.push(
  categories.map((c) => `[${c.name}](#${anchor(c.name)})`).join(" · "),
);
out.push(``);

for (const c of categories) {
  out.push(`## ${c.name}`);
  out.push(``);
  out.push(`| Sample | Class | Topics |`);
  out.push(`|---|---|---|`);
  for (const r of c.rows) {
    out.push(
      `| [${md(r.sub)}](${PLAYGROUND}?app_start=${r.app}) ` +
        `| [\`${r.app}\`](${SOURCE}/${r.app}.js) ` +
        `| ${md(r.keywords)} |`,
    );
  }
  out.push(``);
}

if (uncatalogued.length) {
  out.push(`## Not in the gallery`);
  out.push(``);
  out.push(
    `${uncatalogued.length} further classes ship in the same folder without a catalogue ` +
      `entry — they are the sub-apps the listed samples call (dialogs, detail views, ` +
      `nested apps), not entries in their own right. They run the same way if you name ` +
      `one directly:`,
  );
  out.push(``);
  out.push(uncatalogued.map((a) => `\`${a}\``).join(", "));
  out.push(``);
}

out.push(`## Where they come from`);
out.push(``);
out.push(
  `The samples are machine-transpiled from the ABAP originals in ` +
    `[abap2UI5-samples](https://github.com/abap2UI5/abap2UI5-samples) by the ` +
    `[builder-abap2UI5-js](https://github.com/cap2UI5/builder-abap2UI5-js) pipeline, and ` +
    `land in \`core/srv/app/samples/\` on every sync. That folder is pipeline-owned: ` +
    `edits to it are overwritten on the next publish. Copy a sample into ` +
    `[\`srv/app/\`](./project-structure#srv-app) before you change it.`,
);
out.push(``);
out.push(
  `Some samples need a real server: those that call external OData services or CAP ` +
    `destinations will not work in the browser playground. See ` +
    `[what the playground is not](./playground#what-its-not).`,
);
out.push(``);
out.push(
  `→ Ready to write your own? Start with [Hello World](../examples/hello-world), ` +
    `or read the [App Lifecycle](./lifecycle).`,
);
out.push(``);

const text = out.join("\n");

if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== text) {
    console.error(`gen-samples: ${path.relative(ROOT, OUT)} is out of date — run npm run gen:samples`);
    process.exit(1);
  }
  console.log(`gen-samples: OK — ${path.relative(ROOT, OUT)} matches ${APP}`);
  process.exit(0);
}

fs.writeFileSync(OUT, text);
console.log(
  `gen-samples: wrote ${path.relative(ROOT, OUT)} — ` +
    `${entries.length} catalogued samples in ${categories.length} categories ` +
    `(${files.size} files in ${path.relative(APP, SAMPLES)})`,
);
